### ISSUE TITLE
bug: Type error when running tests for component with onChange listener

### ISSUE THREAD

**Issue by samshareski** [ionic-team/stencil-store#111] opened 2022-06-27 20:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-store/issues) that already report this problem, without success.

### Stencil Store Version

2.0.0

### Stencil Version

2.13.0

### Current Behavior

When a component has an onChange listener which has a function that manipulates a https://github.com/State property:
```typescript
import { onChange } from '../a-store';

export class AppProfile { 
  @State() something = 0;

  componentWillLoad() {
    onChange('clicks', (value) => {
      this.something++;
    });
  }
// ...
}
```
when I try to unit test the component I get a type error like:

 ● app-profile › clicks the button again

    TypeError: Cannot read properties of undefined (reading '$instanceValues$')

      12 |   componentWillLoad() {
      13 |     onChange('clicks', (value) => {
    > 14 |       this.something++;
         |       ^
      15 |     });
      16 |   }
      17 |   

      at getValue (node_modules/@stencil/core/internal/testing/index.js:538:282)
      at AppProfile.get [as something] (node_modules/@stencil/core/internal/testing/index.js:565:13)
      at src/components/app-profile/app-profile.tsx:14:7
      at node_modules/@stencil/store/dist/index.js:144:43
      at node_modules/@stencil/store/dist/index.js:88:40
          at Array.forEach (<anonymous>)
      at reset (node_modules/@stencil/store/dist/index.js:88:24)
      at Object.dispose (node_modules/@stencil/store/dist/index.js:94:9)
      at Object.<anonymous> (src/components/app-profile/app-profile.spec.ts:7:5)
The error only occurs if I'm referencing a @State property, if I reference a component method that just logs something, for example, there is no error.

However, this error doesn't happen with the first test in the suite, only subsequent tests. I'm calling store.dispose() before each test.

### Expected Behavior

Tests should run without throwing an error and failing.

### Steps to Reproduce

Download repo, run `npm install` then `npm run test`

OR

1) Create a component which registers an `onChange` listener that references a `@State` variable

2) Write a unit test suite for the component with at least 2 tests

3) Run the unit tests

### Code Reproduction URL

https://github.com/samshareski/store-test-bug

**Comment by Serabe** [comment] 2022-07-12 16:22
@samshareski are you using `store.dispose()` between tests?

**Comment by samshareski** [comment] 2022-07-12 17:09
> @samshareski are you using `store.dispose()` between tests?

yes

**Comment by Serabe** [comment] 2022-07-12 19:07
Do you have a repo with a reproduction of this issue I can take a look into?

**Comment by samshareski** [comment] 2022-07-12 19:13
> Do you have a repo with a reproduction of this issue I can take a look into?

it's linked in the first comment

**Comment by samshareski** [comment] 2022-07-12 19:15
the failing tests are in this spec https://github.com/samshareski/store-test-bug/blob/master/src/components/app-profile/app-profile.spec.ts

**Comment by Serabe** [comment] 2022-07-12 19:29
I see what's going on. Handlers are never disposed, you need to unregister them in your component.  `onChange` returns a function that when called will unregister everything.

**Comment by samshareski** [comment] 2022-07-12 19:59
@Serabe 
https://github.com/samshareski/store-test-bug/commit/24be6fef71b777f6e3f1b3dfca276b46b2832368
is this how that would be set up?

this version still has the test failures occurring

**Comment by ajgagnon** [comment] 2023-04-05 21:23
@Serabe I believe this is a bug in stencil itself, so I believe this issue can be closed and cross referenced in stencil:

https://github.com/ionic-team/stencil/issues/4053

**Comment by christophsaile** [comment] 2023-06-27 09:29
Hey @ajgagnon, I tried calling  `page.rootInstance.disconnectedCallback();` in my jest test like this: 
``` 
afterEach(() => {
    page.rootInstance.disconnectedCallback();
});
```

unfortunatly I get an `TypeError: page.rootInstance.disconnectedCallback is not a function` after each run. Do you maybe have a working example?

**Comment by ajgagnon** [comment] 2023-09-07 13:15
@christophsaile This is probably because you do not have a disconnectedCallback in your component. You need to add this method to your component:

```js
private removeListener: any;

componentWillLoad() {
    this.removeListener = onChange('clicks', (value) => {
      this.something++;
    });
 }

disconnectedCallback() {
   this.removeListener();
}
```

**Comment by tanner-reits** [comment] 2024-07-18 18:52
Sounds like there is a resolution to this issue. Going to close this out. If there is still a problem along these lines, please open a new issue using the latest versions. Thanks!

**Closed by tanner-reits** 2024-07-18 18:52 UTC
Labels: Resolution: Refine
