### ISSUE TITLE
Data Leak between instances

### ISSUE THREAD

**Issue by dnepro** [ionic-team/stencil-store#39] opened 2020-12-01 12:43 UTC
## Used versions

@stencil/store - v1.3.0
@stencil/core - v2.2.0

## Problem description

I have a use case, where i have to use a component with @stencil/store, multiple times on the same page.
The Problem is that they leak state into each other, is this a known bug?

It would be awesome if each instance had an own store, either by passing the component a key or if it would be possible to create a nested store (get/set nested values).

If a demo repository is helpful just let me know

**Comment by Serabe** [comment] 2020-12-01 12:46
Yeah, please, add a sample repository because I'm not understanding the scenario. That would be most helpful.

Thank you!

**Comment by dnepro** [comment] 2020-12-01 13:55
Here is an Example Repo: https://github.com/dnepro/stencil-store-error

**Comment by Serabe** [comment] 2020-12-02 01:03
Hi!

Took a look at your repo and that's the expected behaviour. As stated in the README, _"Store is a lightweight shared state library by the StencilJS core team"_, so it is expected to be shared across components if you're using a unique app for the whole app.

If you want each component to have their own state, just use the `@State()` decorator in the internal properties you want to be have like it.

Closing this as the behaviour is expected, just let me know if I'm missing something and this should be reopen.

Thank you!

**Closed by Serabe** 2020-12-02 01:03 UTC

**Comment by dnepro** [comment] 2020-12-03 10:41
I see, i wasn't paying to much attention on this.
Still @Serabe thank you for quickly repsonding 👍
